stat_done
alexrad555/java-explore-with-me pull request #1
Opened 2024-02-28 13:50 UTC by alexrad555

2024-02-29 05:10 UTC, ErkinKasymaliev requested changes
привет, хорошая работа!
оставил пару комментов

2024-02-29 05:10 UTC, ErkinKasymaliev commented on stats/stats-dto/src/main/java/ru/practicum/stats/dto/StatData.java
> +                    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime timestamp) {
эту аннотацию можно убрать над полем timestamp и удалить конструктор

2024-02-29 05:10 UTC, ErkinKasymaliev commented on stats/stats-dto/src/main/java/ru/practicum/stats/dto/StatResponse.java
> +            @JsonProperty("app") String app,
аннотации можно убрать над полями и удалить конструктор

2024-02-29 11:13 UTC, alexrad555 commented on stats/stats-dto/src/main/java/ru/practicum/stats/dto/StatData.java
> +                    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime timestamp) {
конструктор убрать нельзя, потому что jackson пытается для десериализации использовать конструктор по умолчанию и сеттеры, а DTO задуманы как Immutable и такой подход к заполнению нам не подходит

2024-02-29 11:13 UTC, alexrad555 commented on stats/stats-dto/src/main/java/ru/practicum/stats/dto/StatResponse.java
> +            @JsonProperty("app") String app,
конструктор убрать нельзя, потому что jackson пытается для десериализации использовать конструктор по умолчанию и сеттеры, а DTO задуманы как Immutable и такой подход к заполнению нам не подходит

2024-02-29 11:15 UTC, alexrad555 commented on stats/stats-dto/src/main/java/ru/practicum/stats/dto/StatResponse.java
> +            @JsonProperty("app") String app,
А как мне ее сдать, просто всего две попытки дается на сдачу, напиши пожалуйста, может и так нормально

2024-03-01 04:37 UTC, ErkinKasymaliev commented on stats/stats-dto/src/main/java/ru/practicum/stats/dto/StatData.java
> +                    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime timestamp) {
хорошо, так тоже пойдет

2024-03-01 04:37 UTC, ErkinKasymaliev commented on stats/stats-dto/src/main/java/ru/practicum/stats/dto/StatResponse.java
> +            @JsonProperty("app") String app,
хорошо, так тоже пойдет

2024-03-01 06:45 UTC, alexrad555 commented on stats/stats-dto/src/main/java/ru/practicum/stats/dto/StatData.java
> +                    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime timestamp) {
спасибо

2024-03-01 06:45 UTC, alexrad555 commented on stats/stats-dto/src/main/java/ru/practicum/stats/dto/StatResponse.java
> +            @JsonProperty("app") String app,
спасибо

2024-03-01 07:10 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2024-03-01 07:34 UTC, merged